POST http://127.0.0.1:3000/api/regisztracio
Content-Type: application/json

{
    "email": "adf@gmail.com",
    "felhasznaloNev": "hashTest",
    "jelszo": "asd123"
}
###
POST http://127.0.0.1:3000/api/belepes
Content-Type: application/json

{
    "felhasznalo": "adf@gmail.com",
    "jelszo": "asd1234"
}
###
GET http://127.0.0.1:3000/api/lekeres
Content-Type: application/json

{
    "table":"koktél",
    "params":"Felhasználónév,KeszitesDatuma,COUNT(HovaIrták) as KommentekSzáma",
    "filter":"where koktél.Keszito like ?",
    "joins":"inner join felhasználó on felhasználó.FelhID=koktél.Keszito inner join ertekeles on koktél.KoktélID=ertekeles.HovaIrták",
    "value":"2"
}

