POST http://127.0.0.1:3000/api/regisztracio
Content-Type: application/json

{
    "email": "adf@gmail.com",
    "felhasznaloNev": "hashTest",
    "jelszo": "asd123"
}
###
POST http://127.0.0.1:3000/api/belepes
Content-Type: application/json

{
    "felhasznalo": "adf@gmail.com",
    "jelszo": "asd1234"
}

