POST http://127.0.0.1:3000/api/regisztracio
Content-Type: application/json

{
    "email": "asd@gmail.com",
    "felhasznaloNev": "hashTest",
    "jelszo": "asd123"
}
###
POST http://127.0.0.1:3000/api/belepes
Content-Type: application/json

{
    "felhasznalo": "test@gmail.com",
    "jelszo": "test123"
}

